version: '3'

services:
  server1:
    container_name: server1
    build: .
#    image: chyun257634/road
#    ports:
#      - 8080:8080
    expose:
      - 8080
    networks:
      - shop_net

  server2:
    container_name: server2
    build: .
#    image: chyun257634/road
#    ports:
#      - 8081:8080
    expose:
      - 8080
    networks:
      - shop_net

  server3:
    container_name: server3
    build: .
    #    image: chyun257634/road
#    ports:
#      - 8082:8080
    expose:
      - 8080
    networks:
      - shop_net

  nginx:
    container_name: nginx
#    build: .
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    depends_on:
      - server1
      - server2
      - server3
    restart:
      always
    networks:
      - shop_net

networks:
  shop_net:
